force-app/main/default/objects/Customer_Success_Story__c/Customer_Success_Story__c.object-meta.xml
<CustomObject>
    <label>Customer Success Story</label>
    <nameField>
        <label>Customer Success Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Success Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Success_Story__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account which this customer success story belongs to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Success Stories</relationshipLabel>
    <relationshipName>Customer_Success_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Ranking Among all success stories on an account</description>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CSSTriggerHelper_Clean.cls
public class CSSTriggerHelper_Clean {
    
    public static Boolean isFirstTime=true;


    public CSSTriggerHelper_Clean(List<Customer_Success_Story__c> cssTrig)
    {
        Set<Id> accIdList= new Set<Id>();

        for(Customer_Success_Story__c c:cssTrig)
        {
            accIdList.add(c.Account__c);
        }

        List<Account> accCompile= [SELECT Id, (SELECT Account__c, Rating__c,Ranking__c FROM Customer_Success_Stories__r ORDER BY Rating__c DESC NULLS LAST) FROM Account WHERE Account.Id IN :accIdList];
        //System.debug(accCompile);
        List<Customer_Success_Story__c> updated=new List<Customer_Success_Story__c>();
        for(Account acc:accCompile)
        {
            Integer inc=1;
            for( Customer_Success_Story__c c:acc.Customer_Success_Stories__r)
            {
                if(inc>1&&c.Rating__c==acc.Customer_Success_Stories__r[inc-2].Rating__c)
                c.Ranking__c=acc.Customer_Success_Stories__r[inc-2].Ranking__c;
                else
                c.Ranking__c=inc;
                updated.add(c);
                System.debug(c);
                inc++;
            }
        }

        update(updated);
        isFirstTime=true;
    }

}