force-app/main/default/objects/Customer_Success_Story__c/Customer_Success_Story__c.object-meta.xml
<CustomObject>
    <label>Customer Success Story</label>
    <nameField>
        <label>Customer Success Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Success Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Success_Story__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Ranking Among all success stories on an account</description>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CSSTriggerHelper.cls
public class CSSTriggerHelper {
    


   public CSSTriggerHelper(List<Customer_Success_Story__c> cssList)
   {
    //List<Customer_Success_Story__c> cssList= cssMap.values();
        Integer numCSS= cssList.size();
        //List<Integer> sameasPrev =new List<Integer>[numCSS];//use later to define ties as the same rating

        //List<Customer_Success_Story__c> sortedList= new List<Customer_Success_Story__c[numCSS];
       // quicksortCSS(cssList,0,numCSS);

        List<Decimal> ratingsVals=new List<Decimal>();

        for(Customer_Success_Story__c CS_S:cssList)
        {
            ratingsVals.add(CS_S.Rating__c);
        }

        ratingsVals.sort();

        for(Customer_Success_Story__c CS_S:cssList)
        {
            for(Integer c=0;c<numCSS;c++)
            {
                //CS_S.Ranking__c=numCSS;
                if(ratingsVals[c]==CS_S.Rating__c)//if the               ating is the same as the value of a sorted rating
                {
                   System.debug(CS_S);
                    CS_S.Ranking__c=c+1;//set theranking to the list value (+1)
                    c=numCSS;//break the for loop
                }
            }
        }
        
        update(cssList);
   }

  /* public static void quicksortCSS(List<Customer_Success_Story__c> cssList,Integer lo, Integer hi)
   {


   }
   public static Integer partition(List<Customer_Success_Story__c> cssList,Integer lo, Integer hi)
   {



   }*/

}