force-app/main/default/objects/Account/fields/Average_Success_Story_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Success_Story_Rating__c</fullName>
    <formula>combined_success_score__c /Num_success_stories__c</formula>
    <label>Average Success Story Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/Customer_Success_Story__c.object-meta.xml
<CustomObject>
    <label>Customer Success Story</label>
    <nameField>
        <label>Customer Success Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Success Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Success_Story__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account which this customer success story belongs to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Success Stories</relationshipLabel>
    <relationshipName>Customer_Success_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Ranking Among all success stories on an account</description>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Success_Story__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CSSTriggerTester.cls
@isTest
public class CSSTriggerTester {

    @TestSetup
    static void createCSSTestData(){
        Account a= new Account(Name= 'tester account for CSS');
        
        insert a;
    }

    @isTest
    public static void cssTestMethod(){
    Account ac= [Select Id,Average_Success_Story_Rating__c FROM Account WHERE Name='tester account for CSS'];

        System.debug('Starting Avg rating: '+ac.Average_Success_Story_Rating__c);
        //good to have here to implement ratings
        Customer_Success_Story__c custa=new Customer_Success_Story__c(Account__c=ac.Id,Name='tester success a',Rating__c=4.5);
        Customer_Success_Story__c custb=new Customer_Success_Story__c(Account__c=ac.Id,Name='tester success b',Rating__c=4.5);
        Customer_Success_Story__c custc=new Customer_Success_Story__c(Account__c=ac.Id,Name='tester success a',Rating__c=5);
        Customer_Success_Story__c custd=new Customer_Success_Story__c(Account__c=ac.Id,Name='tester success d',Rating__c=4);
        insert custa;
        //System.debug(a+' custa: '+custa);
        insert custb;
       // System.debug(a+' \ncusta: '+custa+' \ncustb: '+custb);
        insert custc;
        //System.debug(a+' \tcusta: '+custa+' \tcustb: '+custb+' \tcustc: '+custc);
        insert custd;
        System.debug(ac+' custa: '+custa+' custb: '+custb+' custc: '+custc+' custd: '+custd);

        custa.Rating__c=5;
        update custa;
        
        System.debug(' custa: '+custa+'ranking'+custa.ranking__c);
        delete custc;
        System.debug(' custa: '+custa+' custb: '+custb+' custc: '+custc+' custd: '+custd);
        undelete custc;
        System.debug(' custa: '+custa+' custb: '+custb+' custc: '+custc+' custd: '+custd);







    }
}